services:
  dev:
    # --------------------------------------------------------
    # このディレクトリの Dockerfile からイメージをビルドする
    # --------------------------------------------------------
    build:
      context: ..
      dockerfile: docker/dockerfile

    # --------------------------------------------------------
    # コンテナ名
    # --------------------------------------------------------
    # 任意。なくてもよい。
    # 複数プロジェクトで同じ名前を使うと衝突するので注意。
    container_name: my-python-dev

    # --------------------------------------------------------
    # コンテナ内の作業ディレクトリ
    # --------------------------------------------------------
    # コンテナに入ったとき、基本的に /home/app にいる状態にする。
    # uv sync や git コマンドも、この場所で実行する想定。
    working_dir: /workspace

    # --------------------------------------------------------
    # バインドマウント
    # --------------------------------------------------------
    # ホストPCの現在ディレクトリ . を、コンテナ内の /home/app にマウントする。
    #
    # つまり:
    #   ホストPCのプロジェクトフォルダ
    #     ⇔ コンテナ内の /home/app
    #
    # コンテナ内で /home/app/pyproject.toml として見えているものは、
    # DockerfileでCOPYしたものではなく、ホストPC側のファイル。
    volumes:
      - ..:/workspace

    # --------------------------------------------------------
    # 環境変数ファイル
    # --------------------------------------------------------
    # .bashrcに書くようにするので、今回は不要
    # .env はGitに上げない。
    # .env.example をGitに上げて、各PCで .env を作る運用にする。
    #
    # .env がまだ無い場合、compose実行時にエラーになることがある。
    # その場合は以下を作る:
    #
    #   cp .env.example .env
    #
    #env_file:
    #  - .env

    # --------------------------------------------------------
    # ポート公開
    # --------------------------------------------------------
    # Streamlit を使う想定。
    #
    # ホストPCの 8501
    #   → コンテナ内の 8501
    #
    # Streamlit起動時は以下のように 0.0.0.0 で待ち受ける:
    #
    #   uv run streamlit run app/main.py --server.address=0.0.0.0
    #
    ports:
      - "8501:8501"

    # --------------------------------------------------------
    # コンテナを起動しっぱなしにする
    # --------------------------------------------------------
    # DockerfileにCMDを書かない開発用構成なので、
    # 何もしないとコンテナがすぐ終了する可能性がある。
    #
    # sleep infinity により、開発用コンテナを常駐させる。
    command: sleep infinity
  
    # --------------------------------------------------------
    # 対話操作をしやすくする
    # --------------------------------------------------------
    # docker compose exec dev bash で入ったときに扱いやすくする。
    tty: true
    stdin_open: true